### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by Lusindiso** [Lusindiso/Javascript-Capstone#21]
- https://github.com/Lusindiso/Javascript-Capstone
- There are 2 students in this group.

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @Lusindiso and @Lusindiso,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] For all group tasks please assign both of you to these tasks not a single one only, So please fix that.

![image](https://user-images.githubusercontent.com/68796232/168620244-ef84c969-24c1-4677-add6-4fce3e0d2a13.png)

- [ ] I can see that one of the cards is not assigned to anyone so please fix that.

![image](https://user-images.githubusercontent.com/68796232/168620596-e6331814-c4dc-442f-b7d0-302c8d366c1c.png)


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Lusindiso** [comment]
Hi @Omar-Muhamad 
We have assigned ourselves in the issues, How do we also change it in the kanban?

**Comment by Lusindiso** [comment]
Hi @Omar-Muhamad 
On my side it shows as assigned in the kanban
![Screenshot from 2022-05-16 16-51-54](https://user-images.githubusercontent.com/31928865/168621516-d5cd403b-bee6-4eb3-bb20-fc69663dd450.png)

**Comment by Lusindiso** [comment]
@Omar-Muhamad 
Sorry I didn't see there was an unassigned card, I will fix it, Thank you.

**Comment by GzimAsani** [comment]
# Changes Required :recycle: 

### As asked by the previous reviewer, please assign group tasks to both of you.


 ## [Optional] suggestions:
 * Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 **Cheers and Happy coding!clapclapclap**
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by brytebee** [comment]
Hi Team👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
